-- OPT-IN secondary muscle enrichment (proposal — NOT applied by the import).
-- Generated by scripts/propose-secondary-enrichment.py. Conservative:
-- compound synergists only, for exercises that had no secondary in the CSV.
-- Review, then run against the DB to apply. Idempotent.

-- 125 proposed additions

insert into public.exercise_muscle_groups (exercise_id, muscle_group_id, role)
select e.id, mg.id, 'secondary'
from (values
  (110, 'triceps'),  -- Machine Shoulder Press [shoulders] — vertical pressing locks out through the triceps
  (236, 'glutes'),  -- Hack Squat [quads] — loaded knee+hip extension also drives the glutes
  (130, 'biceps'),  -- Seated Cable Row [back] — rows and vertical pulls recruit the biceps as synergist
  (68, 'triceps'),  -- Dumbbell Shoulder Press (Seated) [shoulders] — vertical pressing locks out through the triceps
  (60, 'triceps'),  -- Dumbbell Press (Low Incline) [chest] — horizontal/incline press + dip drive the triceps
  (11, 'glutes'),  -- Barbell Squat (Close Stance, Feet Forward) [quads] — loaded knee+hip extension also drives the glutes
  (67, 'biceps'),  -- Dumbbell Row to Hips [back] — rows and vertical pulls recruit the biceps as synergist
  (85, 'biceps'),  -- Hammer Machine Row (Low) [back] — rows and vertical pulls recruit the biceps as synergist
  (84, 'biceps'),  -- Hammer Machine Row (High) [back] — rows and vertical pulls recruit the biceps as synergist
  (128, 'hamstrings'),  -- Reverse Lunge (Barbell) [glutes] — hip extension shares load with the hamstrings
  (149, 'hamstrings'),  -- Walking Lunges (Glute-Focused, Bodyweight) [glutes] — hip extension shares load with the hamstrings
  (136, 'triceps'),  -- Smith Machine Bench Press (Medium Grip) [chest] — horizontal/incline press + dip drive the triceps
  (15, 'hamstrings'),  -- Barbell Squat (Sumo Stance) [glutes] — hip extension shares load with the hamstrings
  (43, 'hamstrings'),  -- Deadlift (Deficit) [glutes] — hip extension shares load with the hamstrings
  (119, 'glutes'),  -- Power Squat [quads] — loaded knee+hip extension also drives the glutes
  (71, 'hamstrings'),  -- Dumbbell Split Squat [glutes] — hip extension shares load with the hamstrings
  (3, 'biceps'),  -- Assisted Pullup (Normal Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (4, 'biceps'),  -- Assisted Pullup (Parallel Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (120, 'biceps'),  -- Pull Down (Mag Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (94, 'triceps'),  -- Machine Chest Press [chest] — horizontal/incline press + dip drive the triceps
  (118, 'glutes'),  -- Pendulum Squat [quads] — loaded knee+hip extension also drives the glutes
  (135, 'glutes'),  -- Slope squat [quads] — loaded knee+hip extension also drives the glutes
  (141, 'glutes'),  -- Smith Machine Squat (Feet Forward) [quads] — loaded knee+hip extension also drives the glutes
  (122, 'biceps'),  -- Pulldown (Parallel Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (20, 'hamstrings'),  -- Booty Builder Hip Thrust [glutes] — hip extension shares load with the hamstrings
  (10, 'glutes'),  -- Barbell Split Squat [quads] — loaded knee+hip extension also drives the glutes
  (80, 'hamstrings'),  -- GluteBuilder Hip Thrust [glutes] — hip extension shares load with the hamstrings
  (1, 'triceps'),  -- Arnold Press [shoulders] — vertical pressing locks out through the triceps
  (82, 'forearms'),  -- Hammer Curl [biceps] — neutral/pronated curls bias the forearm flexors
  (41, 'biceps'),  -- Chest Supported Row [back] — rows and vertical pulls recruit the biceps as synergist
  (65, 'biceps'),  -- Dumbbell Row (2-Arm, Incline) [back] — rows and vertical pulls recruit the biceps as synergist
  (104, 'biceps'),  -- Machine Mid Row [back] — rows and vertical pulls recruit the biceps as synergist
  (72, 'glutes'),  -- Dumbbell Stiff Legged Deadlift [hamstrings] — hip-hinge pulls share load with the glutes
  (12, 'glutes'),  -- Barbell Squat (Heel Elevated) [quads] — loaded knee+hip extension also drives the glutes
  (242, 'glutes'),  -- Smith Machine Split Squat [quads] — loaded knee+hip extension also drives the glutes
  (139, 'triceps'),  -- Smith Machine Shoulder Press (Seated) [shoulders] — vertical pressing locks out through the triceps
  (116, 'biceps'),  -- MaxPump Seated Multi High Row (Single Arm) [back] — rows and vertical pulls recruit the biceps as synergist
  (124, 'biceps'),  -- Pulldown (Wide Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (125, 'biceps'),  -- Pullup (Weighted, Normal Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (103, 'biceps'),  -- Machine Low Row [back] — rows and vertical pulls recruit the biceps as synergist
  (115, 'triceps'),  -- MaxPump Incline Press [chest] — horizontal/incline press + dip drive the triceps
  (89, 'glutes'),  -- Leg Press (Watson Split Leg Press) [quads] — loaded knee+hip extension also drives the glutes
  (144, 'triceps'),  -- Standing Shoulder Press (Machine) [shoulders] — vertical pressing locks out through the triceps
  (95, 'triceps'),  -- Machine Chest Press (Incline) [chest] — horizontal/incline press + dip drive the triceps
  (145, 'glutes'),  -- StIff Leg Deadlift [hamstrings] — hip-hinge pulls share load with the glutes
  (26, 'forearms'),  -- Cable Hammer Curl (Rope) [biceps] — neutral/pronated curls bias the forearm flexors
  (148, 'hamstrings'),  -- Walking Lunges (Glute-Focused, Barbell) [glutes] — hip extension shares load with the hamstrings
  (152, 'biceps'),  -- Assisted Pullup (Underhand Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (153, 'biceps'),  -- Assisted Pullup (Wide Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (157, 'biceps'),  -- Barbell Bent Over Row [back] — rows and vertical pulls recruit the biceps as synergist
  (172, 'biceps'),  -- Barbell Row to Chest [back] — rows and vertical pulls recruit the biceps as synergist
  (213, 'biceps'),  -- Cambered Bar Row [back] — rows and vertical pulls recruit the biceps as synergist
  (248, 'biceps'),  -- EZ Bar Row (Underhand) [back] — rows and vertical pulls recruit the biceps as synergist
  (269, 'biceps'),  -- Inverted Row [back] — rows and vertical pulls recruit the biceps as synergist
  (272, 'biceps'),  -- Landmine Row [back] — rows and vertical pulls recruit the biceps as synergist
  (276, 'biceps'),  -- Meadows Row [back] — rows and vertical pulls recruit the biceps as synergist
  (280, 'biceps'),  -- Pulldown (Narrow Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (281, 'biceps'),  -- Pulldown (Single-Arm) [back] — rows and vertical pulls recruit the biceps as synergist
  (282, 'biceps'),  -- Pulldown (Underhand Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (283, 'biceps'),  -- Pulldown (Upright Torso to Abs) [back] — rows and vertical pulls recruit the biceps as synergist
  (284, 'biceps'),  -- Pullup (Normal Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (285, 'biceps'),  -- Pullup (Parallel Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (286, 'biceps'),  -- Pullup (Underhand Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (287, 'biceps'),  -- Pullup (Weighted, Parallel Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (288, 'biceps'),  -- Pullup (Weighted, Underhand Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (289, 'biceps'),  -- Pullup (Weighted, Wide Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (290, 'biceps'),  -- Pullup (Wide Grip) [back] — rows and vertical pulls recruit the biceps as synergist
  (302, 'biceps'),  -- Seal Row [back] — rows and vertical pulls recruit the biceps as synergist
  (303, 'biceps'),  -- Seated Cable Row (Single-Arm) [back] — rows and vertical pulls recruit the biceps as synergist
  (320, 'biceps'),  -- Smith Machine Row [back] — rows and vertical pulls recruit the biceps as synergist
  (325, 'biceps'),  -- T-Bar Row [back] — rows and vertical pulls recruit the biceps as synergist
  (264, 'forearms'),  -- Hammer Preacher Curl [biceps] — neutral/pronated curls bias the forearm flexors
  (182, 'triceps'),  -- Bench Press (Cambered Bar) [chest] — horizontal/incline press + dip drive the triceps
  (184, 'triceps'),  -- Bench Press (Decline) [chest] — horizontal/incline press + dip drive the triceps
  (185, 'triceps'),  -- Bench Press (Incline, Narrow Grip) [chest] — horizontal/incline press + dip drive the triceps
  (186, 'triceps'),  -- Bench Press (Incline, Wide Grip) [chest] — horizontal/incline press + dip drive the triceps
  (187, 'triceps'),  -- Bench Press (Narrow Grip) [chest] — horizontal/incline press + dip drive the triceps
  (188, 'triceps'),  -- Bench Press (Wide Grip) [chest] — horizontal/incline press + dip drive the triceps
  (193, 'triceps'),  -- Cable Chest Press [chest] — horizontal/incline press + dip drive the triceps
  (221, 'triceps'),  -- Dip (Chest-Focused) [chest] — horizontal/incline press + dip drive the triceps
  (222, 'triceps'),  -- Dip (Weighted, Chest-Focused) [chest] — horizontal/incline press + dip drive the triceps
  (263, 'triceps'),  -- Hammer Machine Chest Press (Incline) [chest] — horizontal/incline press + dip drive the triceps
  (291, 'triceps'),  -- Pushup (Deficit) [chest] — horizontal/incline press + dip drive the triceps
  (292, 'triceps'),  -- Pushup (Narrow Grip) [chest] — horizontal/incline press + dip drive the triceps
  (293, 'triceps'),  -- Pushup (Weighted, Narrow Grip) [chest] — horizontal/incline press + dip drive the triceps
  (294, 'triceps'),  -- Pushup (Weighted, Normal Grip) [chest] — horizontal/incline press + dip drive the triceps
  (308, 'triceps'),  -- Smith Machine Bench Press (Narrow Grip) [chest] — horizontal/incline press + dip drive the triceps
  (309, 'triceps'),  -- Smith Machine Bench Press (Wide Grip) [chest] — horizontal/incline press + dip drive the triceps
  (311, 'triceps'),  -- Smith Machine Press (High Incline, Medium Grip) [chest] — horizontal/incline press + dip drive the triceps
  (312, 'triceps'),  -- Smith Machine Press (High Incline, Narrow Grip) [chest] — horizontal/incline press + dip drive the triceps
  (313, 'triceps'),  -- Smith Machine Press (High Incline, Wide Grip) [chest] — horizontal/incline press + dip drive the triceps
  (316, 'triceps'),  -- Smith Machine Press (Low Incline, Medium Grip) [chest] — horizontal/incline press + dip drive the triceps
  (317, 'triceps'),  -- Smith Machine Press (Low Incline, Narrow Grip) [chest] — horizontal/incline press + dip drive the triceps
  (318, 'triceps'),  -- Smith Machine Press (Low Incline, Wide Grip) [chest] — horizontal/incline press + dip drive the triceps
  (319, 'triceps'),  -- Smith Machine Press (Medium Incline, Narrow Grip) [chest] — horizontal/incline press + dip drive the triceps
  (190, 'hamstrings'),  -- Bulgarian Split Squat (Glute-Focused) [glutes] — hip extension shares load with the hamstrings
  (204, 'hamstrings'),  -- Cable Pull Through [glutes] — hip extension shares load with the hamstrings
  (216, 'hamstrings'),  -- Deadlift (Deficit 25''s) [glutes] — hip extension shares load with the hamstrings
  (218, 'hamstrings'),  -- Deadlift (Sumo Stance) [glutes] — hip extension shares load with the hamstrings
  (219, 'hamstrings'),  -- Deadlift (Sumo Stance, Deficit) [glutes] — hip extension shares load with the hamstrings
  (232, 'hamstrings'),  -- Dumbbell Hip Thrust (Single Leg) [glutes] — hip extension shares load with the hamstrings
  (258, 'hamstrings'),  -- Front Foot Elevated Smith Lunge [glutes] — hip extension shares load with the hamstrings
  (298, 'hamstrings'),  -- Reverse Lunge (Dumbbell) [glutes] — hip extension shares load with the hamstrings
  (300, 'hamstrings'),  -- Rogers Reverse Lunge [glutes] — hip extension shares load with the hamstrings
  (326, 'hamstrings'),  -- Trap Bar Deadlift [glutes] — hip extension shares load with the hamstrings
  (328, 'hamstrings'),  -- Walking Lunges (Glute-Focused, Dumbbell) [glutes] — hip extension shares load with the hamstrings
  (305, 'glutes'),  -- Single Leg Romanian Deadlift [hamstrings] — hip-hinge pulls share load with the glutes
  (176, 'glutes'),  -- Barbell Squat (Cambered Bar) [quads] — loaded knee+hip extension also drives the glutes
  (177, 'glutes'),  -- Barbell Squat (Safety Bar) [quads] — loaded knee+hip extension also drives the glutes
  (189, 'glutes'),  -- Bodyweight Squat (2/3) [quads] — loaded knee+hip extension also drives the glutes
  (191, 'glutes'),  -- Bulgarian Split Squat (Quad-Focused) [quads] — loaded knee+hip extension also drives the glutes
  (231, 'glutes'),  -- Dumbbell Front Squat [quads] — loaded knee+hip extension also drives the glutes
  (259, 'glutes'),  -- Front Squat [quads] — loaded knee+hip extension also drives the glutes
  (260, 'glutes'),  -- Front Squat (Cross Grip) [quads] — loaded knee+hip extension also drives the glutes
  (261, 'glutes'),  -- Goblet Squat [quads] — loaded knee+hip extension also drives the glutes
  (301, 'glutes'),  -- Rogers Squat [quads] — loaded knee+hip extension also drives the glutes
  (304, 'glutes'),  -- Single Leg Press [quads] — loaded knee+hip extension also drives the glutes
  (329, 'glutes'),  -- Walking Lunges (Quad-Focused, Barbell) [quads] — loaded knee+hip extension also drives the glutes
  (330, 'glutes'),  -- Walking Lunges (Quad-Focused, Dumbbell) [quads] — loaded knee+hip extension also drives the glutes
  (173, 'triceps'),  -- Barbell Shoulder Press (Seated) [shoulders] — vertical pressing locks out through the triceps
  (174, 'triceps'),  -- Barbell Shoulder Press (Standing) [shoulders] — vertical pressing locks out through the triceps
  (241, 'triceps'),  -- Dumbbell Shoulder Press (Standing) [shoulders] — vertical pressing locks out through the triceps
  (183, 'chest'),  -- Bench Press (Close Grip) [triceps] — close-grip pressing involves the chest
  (271, 'chest'),  -- JM Press [triceps] — close-grip pressing involves the chest
  (310, 'chest')  -- Smith Machine JM Press [triceps] — close-grip pressing involves the chest
) as p(legacy_id, secondary)
join public.exercises e on e.legacy_id = p.legacy_id and e.user_id is null
join public.muscle_groups mg on mg.name = p.secondary
on conflict (exercise_id, muscle_group_id) do nothing;
