#!/usr/bin/env python3
"""Propose high-confidence secondary muscle groups for library exercises.

OPT-IN. This does NOT run in the import migration. It only proposes a secondary
muscle for exercises that currently have NONE, using conservative movement-pattern
rules (compound synergists only; isolation lifts are left alone). The user's own
hand-curated secondaries are never touched.

Emits scripts/exercise-secondary-enrichment.sql (idempotent, keyed by legacy_id,
`on conflict do nothing`) for review before applying.

Run: python3 scripts/propose-secondary-enrichment.py
"""
from __future__ import annotations

import csv
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSV = ROOT / "docs" / "data" / "exercises_all_20260615.csv"
OUT = ROOT / "scripts" / "exercise-secondary-enrichment.sql"


def has_any(name: str, needles: list[str]) -> bool:
    n = name.lower()
    return any(x in n for x in needles)


def propose(name: str, primary: str) -> tuple[str, str] | None:
    """Return (secondary, rationale) or None. Conservative: compound synergists
    only; returns None for isolation movements."""
    n = name.lower()

    if primary == "chest":
        if has_any(n, ["flye", "fly", "pec dec", "pec deck", "pullover"]):
            return None  # isolation / not triceps-driven
        if has_any(n, ["bench press", "chest press", "incline press",
                       "press (flat", "press (low incline", "press (medium incline",
                       "press (high incline", "dip", "pushup", "push-up", "push up"]):
            return "triceps", "horizontal/incline press + dip drive the triceps"
        return None

    if primary == "back":
        if has_any(n, ["pullover", "straight arm", "shrug", "back raise",
                       "back extension", "scapular", "flexion", "deadlift"]):
            return None  # not elbow-flexion driven
        if has_any(n, ["row", "pulldown", "pull down", "pullup", "pull-up",
                       "pull up", "chin", "pull (mag", "pull down (mag"]):
            return "biceps", "rows and vertical pulls recruit the biceps as synergist"
        return None

    if primary == "quads":
        if has_any(n, ["extension", "sissy", "adduction", "hip adduction"]):
            return None  # knee-extension / adductor isolation
        if has_any(n, ["squat", "leg press", "lunge", "hack", "split squat",
                       "pendulum", "power squat", "slope squat", "belt squat"]):
            return "glutes", "loaded knee+hip extension also drives the glutes"
        return None

    if primary == "hamstrings":
        if has_any(n, ["curl", "nordic", "back raise", "good morning"]):
            return None  # knee-flexion isolation / GM already hip-hinge but spinal
        if has_any(n, ["deadlift", "romanian", "stiff", "sldl"]):
            return "glutes", "hip-hinge pulls share load with the glutes"
        return None

    if primary == "glutes":
        if has_any(n, ["kickback", "abduction", "hip press", "reverse hyper"]):
            return None  # glute isolation
        if has_any(n, ["hip thrust", "deadlift", "sumo", "lunge", "split squat",
                       "pull through", "trap bar", "good morning"]):
            return "hamstrings", "hip extension shares load with the hamstrings"
        return None

    if primary == "shoulders":
        if has_any(n, ["shoulder press", "overhead press", "arnold",
                       "standing shoulder press", "shoulder press (machine"]):
            return "triceps", "vertical pressing locks out through the triceps"
        return None

    if primary == "biceps":
        if has_any(n, ["hammer", "reverse curl"]):
            return "forearms", "neutral/pronated curls bias the forearm flexors"
        return None

    if primary == "triceps":
        if has_any(n, ["close grip", "close-grip", "jm press", "skullcrusher"]):
            return None if "skull" in n else ("chest", "close-grip pressing involves the chest")
        return None

    return None


def main():
    with CSV.open(newline="", encoding="utf-8-sig") as fh:
        rows = list(csv.reader(fh))

    proposals = []
    for r in rows[1:]:
        if not r or not any(c.strip() for c in r):
            continue
        legacy_id = int(r[0])
        name = r[1].strip()
        primary = r[2].strip().lower()
        secondary = r[3].strip().lower()
        if secondary:
            continue  # never override the user's own secondaries
        p = propose(name, primary)
        if p is None:
            continue
        sec, why = p
        if sec == primary:
            continue
        proposals.append((legacy_id, name, primary, sec, why))

    lines = [
        "-- OPT-IN secondary muscle enrichment (proposal — NOT applied by the import).",
        "-- Generated by scripts/propose-secondary-enrichment.py. Conservative:",
        "-- compound synergists only, for exercises that had no secondary in the CSV.",
        "-- Review, then run against the DB to apply. Idempotent.",
        "",
        f"-- {len(proposals)} proposed additions",
        "",
        "insert into public.exercise_muscle_groups (exercise_id, muscle_group_id, role)",
        "select e.id, mg.id, 'secondary'",
        "from (values",
    ]
    for i, (lid, name, primary, sec, why) in enumerate(proposals):
        comma = "," if i < len(proposals) - 1 else ""
        safe = name.replace("'", "''")
        lines.append(f"  ({lid}, '{sec}'){comma}  -- {safe} [{primary}] — {why}")
    lines += [
        ") as p(legacy_id, secondary)",
        "join public.exercises e on e.legacy_id = p.legacy_id and e.user_id is null",
        "join public.muscle_groups mg on mg.name = p.secondary",
        "on conflict (exercise_id, muscle_group_id) do nothing;",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(proposals)} proposed -> {OUT.relative_to(ROOT)}")
    by_primary: dict[str, int] = {}
    for _, _, primary, _, _ in proposals:
        by_primary[primary] = by_primary.get(primary, 0) + 1
    print("by primary:", dict(sorted(by_primary.items())))


if __name__ == "__main__":
    main()
