-- 20260619000001 — engine_params v9: rep-window prescription (doc 13 + §9)
--
-- Activates the doc 13 model: the prescribed weight is chosen so reps land in a
-- per-goal productive window at the week's target RIR (from the recency-weighted
-- strength anchor), reps are graded on RIR (overshooting intensity holds, never
-- regresses), and the anchor is `session_best` (the recency-weighted best set,
-- averaged across that set's session — robust to a lone blow-out set). Strength
-- vs hypertrophy now carry distinct rep windows (3–5 vs 8–12).
--
-- The behavior is param-gated (doc 13 decision 8): `weight_selection` and
-- `grading` flip the engine between the new rep-window/RIR path and the legacy
-- increment/rep-count path, so rolling back is an `engine_params` activation, not
-- a redeploy. Both paths live in code; the increment path is byte-for-byte the v8
-- behavior. The schema gained these fields with legacy-valued defaults, so every
-- pre-v9 row still parses to the increment path — only this active row turns the
-- new model on.
--
-- Adding the rep-window block changes the schema *shape*, so schema_version bumps
-- to 4 (params-provenance.ts). This seeds v9 as a fully materialized v4 snapshot
-- with its canonical sha256 hash (generated by the app's own
-- `engineParamsSchema.parse()` + `hashParams()`), so it replays exactly. v8 and
-- earlier predate the rep-window fields, so under schema v4 their stored bytes are
-- no longer byte-complete materializations and are flagged non-replayable.

-- single-active invariant: deactivate the current active version before insert.
update public.engine_params set is_active = false where is_active = true;

insert into public.engine_params (version, params, is_active, notes, schema_version, params_hash, code_sha, is_replayable)
values (
  9,
  '{"deload":{"load_pct":0.55,"set_pct":0.5,"target_rir":4},"e1rm":{"anchor_method":"session_best","high_max_eff_reps":8,"high_max_rir":2,"mod_max_eff_reps":12,"mod_max_rir":3,"recency_halflife_days":30,"rir_offset":1},"experience_increment_scale":{"advanced":0.5,"beginner":1.5,"intermediate":1},"grading":"rir","increment":{"bands":{"kg":5,"lb":10},"barbell":{"kg":2.5,"lb":5},"bodyweight":{"kg":2.5,"lb":5},"cable":{"kg":2.5,"lb":5},"dumbbell":{"kg":2,"lb":5},"kettlebell":{"kg":4,"lb":9},"machine":{"kg":2.5,"lb":5},"other":{"kg":2.5,"lb":5},"smith":{"kg":2.5,"lb":5}},"key_lifts":{"n":5,"selection":"frequency"},"macro_target":{"age_taper":true,"age_taper_floor":0.6,"age_taper_per_year":0.02,"age_taper_start":40,"career_cap_lb":{"female":20,"male":40},"career_tau_years":3,"cut_bf_thresholds":{"female":{"high":30,"lean":22},"male":{"high":20,"lean":12}},"cut_bmi_high":27,"cut_bmi_lean":22,"cut_cap_pct_bw":0.25,"cut_pct_bw_week":{"average":[0.5,1],"high_bf":[1,1.5],"lean":[0.25,0.5]},"ffmi_ceiling":{"female":21.5,"male":25},"ffmi_untrained":{"female":14.5,"male":18.5},"hypertrophy_base_pct_bw_month":{"high":1.5,"low":1},"hypertrophy_decay_tau_years":5,"hypertrophy_floor_pct_bw_month":{"high":0.09,"low":0.04},"hypertrophy_pct_bw_month":{"advanced":[0.25,0.5],"beginner":[1,1.5],"intermediate":[0.5,1]},"present":"conservative_end","proximity_macro_cap_frac":0.6,"recommend_cut_bw_pct":8,"recommend_max_months":12,"recommend_min_months":2,"recommend_strength_total_pct":10,"recommend_target_lb":{"female":4,"male":8},"sex_factor_female":0.7,"strength_cap_total_pct":{"advanced":15,"beginner":60,"intermediate":30},"strength_pct_month":{"advanced":[0.5,1.5],"beginner":[4,8],"intermediate":[1.5,3]}},"max_sets_per_exercise":6,"meso_seed_backoff_pct":0.925,"mg_set_ceiling":20,"min_sets":2,"pain_gate":2,"phase_plan":{"accumulation_fraction":0.6,"order":["accumulation","intensification","peak"]},"progression_style":{"cut":"hold","gain":"load_first","hypertrophy":"load_first","maintain":"hold","strength":"load_first"},"pump_low":2,"regression_pct":0.9,"rep_window":{"cut":{"max":15,"min":6,"target_high":12,"target_low":8},"gain":{"max":15,"min":6,"target_high":12,"target_low":8},"hypertrophy":{"max":15,"min":6,"target_high":12,"target_low":8},"maintain":{"max":15,"min":6,"target_high":12,"target_low":8},"strength":{"max":6,"min":2,"target_high":5,"target_low":3}},"reps_predict":{"min_confidence":"low"},"rir_regress_gap":2,"rir_tolerance":1,"rounding":{"bands":{"kg":5,"lb":10},"barbell":{"kg":2.5,"lb":5},"bodyweight":{"kg":2.5,"lb":5},"cable":{"kg":2.5,"lb":5},"dumbbell":{"kg":2,"lb":5},"kettlebell":{"kg":4,"lb":9},"machine":{"kg":2.5,"lb":5},"other":{"kg":2.5,"lb":5},"smith":{"kg":2.5,"lb":5}},"session_fatigue_dampen_threshold":3,"session_performance_dampen_threshold":1,"set_add_pump_min":6,"small_miss_reps":2,"volume":{"experience_scale":{"advanced":1.1,"beginner":0.7,"intermediate":1},"landmarks":{"abs":[4,16,25],"back":[10,22,25],"biceps":[6,20,26],"calves":[6,16,20],"chest":[8,20,22],"glutes":[4,16,20],"hamstrings":[6,16,20],"quads":[8,18,20],"shoulders":[8,20,26],"triceps":[6,18,24]}},"weight_selection":"rep_window","workload_high":8,"workload_low":3}'::jsonb,
  true,
  'v9 — rep-window prescription + RIR grading + session_best anchor (doc 13 + §9); per-goal rep windows (strength 3-5 / hypertrophy 8-12). Param-gated: weight_selection=rep_window, grading=rir. Increment path preserved for rollback.',
  4,
  '1e9b0579f4283816c786f92702b0eec56ce45cbab81ef0e24f1140eed397a841',
  null,
  true
)
on conflict (version) do nothing;

-- versions <= 8 predate the rep-window fields, so under schema v4 their stored
-- bytes are no longer byte-complete materializations; flag them non-replayable to
-- match what the reader (resolveProvenance, current schema) now computes.
update public.engine_params set is_replayable = false where version <= 8;
