-- 20260618000001 — engine_params v8: weekly-set volume landmarks (review §5.4)
--
-- The connector could flag *relative* muscle imbalance but had no absolute
-- reference, so it could not say whether a muscle sits below maintenance volume
-- (MEV) or beyond what can be recovered (MRV). `get_muscle_balance` even said so
-- ("MEV/MAV/MRV landmarks are not yet parameterized"). This parameterizes them.
--
-- The engine-params schema gains a `volume` block (10 §2/§8): per-muscle
-- `[MEV, MAV_high, MRV]` weekly direct-equivalent sets (intermediate baseline)
-- plus an `experience_scale` that shifts the whole band by training level. These
-- are heuristic RP/Israetel starting points — tunable, advisory, not gospel
-- (10 §9). They do NOT change `prescribe()` output (the progression engine does
-- not consume landmarks); only `get_muscle_balance` reads them, so live
-- generation is unaffected by activating this version.
--
-- Because adding a defaulted field changes the schema *shape*, the params
-- schema_version is bumped to 3 (params-provenance.ts). To keep P0-3's
-- immutable-snapshot reproducibility intact, this seeds v8 as a fully
-- materialized v3 snapshot (active v6's params + the resolved volume block) with
-- its canonical sha256 hash, rather than relying on read-time defaulting. v6/v7
-- predate the field, so under schema v3 they are no longer byte-complete
-- materializations and are flagged non-replayable (their stored bytes target
-- schema v2). params_hash + the materialized JSON were generated by the app's
-- own `engineParamsSchema.parse()` + `hashParams()` so they match what the
-- reader recomputes.

-- deactivate the current active version first: a partial unique index enforces
-- a single active row, so v8 cannot be inserted active while v6 still is.
update public.engine_params set is_active = false where is_active = true;

insert into public.engine_params (version, params, is_active, notes, schema_version, params_hash, code_sha, is_replayable)
values (
  8,
  '{"increment":{"bands":{"kg":5,"lb":10},"cable":{"kg":2.5,"lb":5},"other":{"kg":2.5,"lb":5},"smith":{"kg":2.5,"lb":5},"barbell":{"kg":2.5,"lb":5},"machine":{"kg":2.5,"lb":5},"dumbbell":{"kg":2,"lb":5},"bodyweight":{"kg":2.5,"lb":5},"kettlebell":{"kg":4,"lb":9}},"experience_increment_scale":{"advanced":0.5,"beginner":1.5,"intermediate":1},"progression_style":{"cut":"hold","gain":"load_first","maintain":"hold"},"small_miss_reps":2,"regression_pct":0.9,"pain_gate":2,"workload_high":8,"workload_low":3,"set_add_pump_min":6,"pump_low":2,"min_sets":2,"max_sets_per_exercise":6,"mg_set_ceiling":20,"session_fatigue_dampen_threshold":3,"session_performance_dampen_threshold":1,"deload":{"load_pct":0.55,"set_pct":0.5,"target_rir":4},"meso_seed_backoff_pct":0.925,"rounding":{"bands":{"kg":5,"lb":10},"cable":{"kg":2.5,"lb":5},"other":{"kg":2.5,"lb":5},"smith":{"kg":2.5,"lb":5},"barbell":{"kg":2.5,"lb":5},"machine":{"kg":2.5,"lb":5},"dumbbell":{"kg":2,"lb":5},"bodyweight":{"kg":2.5,"lb":5},"kettlebell":{"kg":4,"lb":9}},"e1rm":{"rir_offset":1,"high_max_eff_reps":8,"mod_max_eff_reps":12,"high_max_rir":2,"mod_max_rir":3,"recency_halflife_days":30},"macro_target":{"sex_factor_female":0.7,"hypertrophy_base_pct_bw_month":{"low":1,"high":1.5},"hypertrophy_decay_tau_years":5,"hypertrophy_floor_pct_bw_month":{"low":0.04,"high":0.09},"ffmi_ceiling":{"male":25,"female":21.5},"ffmi_untrained":{"male":18.5,"female":14.5},"proximity_macro_cap_frac":0.6,"cut_bf_thresholds":{"male":{"high":20,"lean":12},"female":{"high":30,"lean":22}},"career_cap_lb":{"male":40,"female":20},"career_tau_years":3,"hypertrophy_pct_bw_month":{"beginner":[1,1.5],"intermediate":[0.5,1],"advanced":[0.25,0.5]},"strength_pct_month":{"beginner":[4,8],"intermediate":[1.5,3],"advanced":[0.5,1.5]},"strength_cap_total_pct":{"beginner":60,"intermediate":30,"advanced":15},"cut_pct_bw_week":{"high_bf":[1,1.5],"average":[0.5,1],"lean":[0.25,0.5]},"cut_bmi_high":27,"cut_bmi_lean":22,"cut_cap_pct_bw":0.25,"age_taper":true,"age_taper_start":40,"age_taper_per_year":0.02,"age_taper_floor":0.6,"recommend_target_lb":{"male":8,"female":4},"recommend_strength_total_pct":10,"recommend_cut_bw_pct":8,"recommend_min_months":2,"recommend_max_months":12,"present":"conservative_end"},"phase_plan":{"order":["accumulation","intensification","peak"],"accumulation_fraction":0.6},"key_lifts":{"n":5,"selection":"frequency"},"volume":{"landmarks":{"back":[10,22,25],"chest":[8,20,22],"quads":[8,18,20],"hamstrings":[6,16,20],"glutes":[4,16,20],"shoulders":[8,20,26],"biceps":[6,20,26],"triceps":[6,18,24],"calves":[6,16,20],"abs":[4,16,25]},"experience_scale":{"beginner":0.7,"intermediate":1,"advanced":1.1}}}'::jsonb,
  true,
  'v8 — weekly-set volume landmarks (MEV/MAV/MRV per muscle + experience scale), 10 §2/§8; identical engine behavior to v6, adds the volume block for get_muscle_balance threshold assertions',
  3,
  '0ba7bcab0bc5930f15d80dc9d70cb671dbaaba15343733eae41791949fffd455',
  null,
  true
)
on conflict (version) do nothing;

-- v6/v7 stored bytes predate the volume field, so under schema v3 they are no
-- longer byte-complete materializations; flag them non-replayable to match what
-- the reader (resolveProvenance, current schema) now computes.
update public.engine_params set is_replayable = false where version in (6, 7);
